<?php

namespace LoopAnime\GeneralBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CountriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountriesRepository extends EntityRepository
{
}
