<?php

namespace LoopAnime\ShowsAPIBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AnimesAPIRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnimesAPIRepository extends EntityRepository
{
}
