<?php

namespace LoopAnime\ShowsAPIBundle\Entity;

use Doctrine\ORM\EntityRepository;
use LoopAnime\ShowsBundle\Entity\Animes;

/**
 * AnimesAPIRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnimesAPIRepository extends EntityRepository
{
    /**
     * @param $isAll
     * @param $anime
     * @return Animes
     */
    public function getAnimesToUpdate($isAll = false, $anime = null)
    {

        $query = $this->createQueryBuilder('api')
                    ->select('a.id')
                    ->join('api.anime','a');
        
        if(!$isAll) {
            $query->andWhere('a.status = :status')
                ->setParameter('status', 'Continuing');
        }

        if($anime) {
            $query->andWhere('a.id = :idAnime')
                ->setParameter('idAnime', (int)$anime);
        }

        return $query->getQuery()->getResult();
    }
}
