<?php

namespace LoopAnime\ShowsAPIBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Animes_APIRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Animes_APIRepository extends EntityRepository
{
}
