<?php

namespace LoopAnime\ShowsAPIBundle\Entity;

use LoopAnime\AppBundle\Entity\BaseRepository;

/**
 * APISRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class APISRepository extends BaseRepository
{
}
