<?php

namespace LoopAnime\ShowsAPIBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * APISRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class APISRepository extends EntityRepository
{
}
