<?php

namespace LoopAnime\CommentsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentsRepository extends EntityRepository
{

    public function getCommentsByEpisode($idEpisode, $getResults = true)
    {

        $query = "SELECT c
            FROM
              LoopAnime\CommentsBundle\Entity\Comments c
            where
              c.idEpisode = '$idEpisode'";

        $query = $this->_em->createQuery($query);

        if($getResults) {
            return $query->getResult();
        } else {
            return $query;
        }

    }

}
