<?php

namespace LoopAnime\CommentsBundle\Entity;

use Doctrine\ORM\EntityRepository;
use LoopAnime\ShowsBundle\Entity\Animes;
use LoopAnime\ShowsBundle\Entity\AnimesEpisodes;
use LoopAnime\UsersBundle\Entity\Users;

/**
 * CommentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentsRepository extends EntityRepository
{

    public function getCommentsByEpisode(AnimesEpisodes $episode, $getResults = true)
    {

        $idEpisode = $episode->getId();

        $query = $this->createQueryBuilder("comments")
                    ->select("comments")
                    ->addSelect('u')
                    ->join('comments.user','u')
                    ->where("comments.episode = :idEpisode")
                    ->setParameter("idEpisode", $idEpisode)
                    ->getQuery();

        if($getResults) {
            return $query->getResult();
        } else {
            return $query;
        }

    }

    public function getCommentsByUser(Users $user, $getResults = true)
    {
        $query = $this->createQueryBuilder("comments")
                    ->select("comments")
                    ->where("comments.user = :user")
                    ->setParameter("user", $user)
                    ->getQuery();
        if($getResults) {
            return $query->getResult();
        } else {
            return $query;
        }
    }

    public function getCommentsByAnime(Animes $animes, $getResults = true)
    {
        $query = $this->createQueryBuilder('comments')
                    ->select('comments')
                    ->where('a.id = :idAnime')
                    ->join('comments.episode','ae')
                    ->join('ae.season','ase')
                    ->join('ase.anime', 'a')
                    ->setParameter('idAnime', $animes->getId())
                    ->getQuery();
        if($getResults) {
            return $query->getResult();
        } else {
            return $query;
        }
    }

}
