<?php

namespace LoopAnime\CommentsBundle\Entity;

use Doctrine\ORM\EntityRepository;
use LoopAnime\ShowsBundle\Entity\AnimesEpisodes;
use LoopAnime\UsersBundle\Entity\Users;

/**
 * CommentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentsRepository extends EntityRepository
{

    public function getCommentsByEpisode(AnimesEpisodes $episode, $getResults = true)
    {

        $idEpisode = $episode->getId();

        $query = $this->createQueryBuilder("comments")
                    ->select("comments")
                    ->where("comments.idEpisode = :idEpisode")
                    ->setParameter("idEpisode", $idEpisode)
                    ->getQuery();

        if($getResults) {
            return $query->getResult();
        } else {
            return $query;
        }

    }

    public function getCommentsByUser(Users $user, $getResults = true)
    {
        $idUser = $user->getId();

        $query = $this->createQueryBuilder("comments")
                    ->select("comments")
                    ->where("comments.idUser = :idUser")
                    ->setParameter("idUser", $idUser)
                    ->getQuery();
        if($getResults) {
            return $query->getResult();
        } else {
            return $query;
        }
    }

}
