<?php

namespace LoopAnime\ShowsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Animes_LinksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnimesLinksRepository extends EntityRepository
{

    public function getLinksByEpisode($idEpisode, $getResults = true)
    {

        $query = "SELECT al
                FROM
                    LoopAnime\ShowsBundle\Entity\AnimesLinks al
                WHERE
                    al.idEpisode = '".$idEpisode."'";
        if($getResults)
            return $this->_em->createQuery($query)->getResult();
        else
            return $this->_em->createQuery($query);

    }

}
