<?php

namespace LoopAnime\ShowsBundle\Entity;

use LoopAnime\AppBundle\Entity\BaseRepository;

/**
 * Animes_TrackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnimesTrackRepository extends BaseRepository
{
}
