<?php

namespace LoopAnime\ShowsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Animes_SeasonsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnimesSeasonsRepository extends EntityRepository
{

    public function getTotSeasons(Animes $anime)
    {
        $query = $this->createQueryBuilder("ase")
            ->select("COUNT(ase)")
            ->where("ase.idAnime = :idAnime")
            ->setParameter("idAnime", $anime->getId())
            ->getQuery();
        return $query->getSingleScalarResult();
    }

    /**
     * @param $idAnime
     * @param bool $getResults
     * @return array|\Doctrine\ORM\Query
     */
    public function getSeasonsByAnime($idAnime, $getResults = true) {
        $query = $this->createQueryBuilder('ase')
                ->select('ase')
                ->join('ase.animes','a')
                ->where('a.id = :idAnime')
                ->setParameter('idAnime',$idAnime);

        if($getResults)
            return $query->getQuery()->getResult();
        else
            return $query->getQuery();
    }

    public function getSeasonById($idSeason, $getResults = true)
    {

        $query = "SELECT ase
                FROM
                    LoopAnime\ShowsBundle\Entity\AnimesSeasons ase
                WHERE
                    ase.id = '".$idSeason."'";
        if($getResults)
            return $this->_em->createQuery($query)->getSingleResult();
        else
            return $this->_em->createQuery($query);

    }

}
