<?php

namespace LoopAnime\ShowsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Animes_SeasonsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnimesSeasonsRepository extends EntityRepository
{

    public function getTotSeasons(Animes $anime)
    {
        $query = $this->createQueryBuilder("ase")
            ->select("COUNT(ase)")
            ->where("ase.anime = :idAnime")
            ->setParameter("idAnime", $anime->getId())
            ->getQuery();
        return $query->getSingleScalarResult();
    }

    /**
     * @param $idAnime
     * @param bool $getResults
     * @return array|\Doctrine\ORM\Query
     */
    public function getSeasonsByAnime($idAnime, $getResults = true)
    {
        $query = $this->createQueryBuilder('ase')
                ->select('ase')
                ->join('ase.anime','a')
                ->where('a.id = :idAnime')
                ->setParameter('idAnime',$idAnime);

        if($getResults)
            return $query->getQuery()->getResult();
        else
            return $query->getQuery();
    }

    public function getSeasonById(AnimesSeasons $idSeason, $getResults = true)
    {
        $query = $this->createQueryBuilder('ase')
            ->select('ase')
            ->where('ase.id = :idSeason')
            ->setParameter('idSeason',$idSeason->getId());

        if($getResults)
            return $query->getQuery()->getSingleResult();
        else
            return $query->getQuery();

    }

}
