<?php

namespace LoopAnime\UsersBundle\Entity;

use LoopAnime\AppBundle\Entity\BaseRepository;

/**
 * CountriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountriesRepository extends BaseRepository
{
}
