<?php

namespace LoopAnime\UsersBundle\Entity;

use LoopAnime\AppBundle\Entity\BaseRepository;

/**
 * Users_PreferencesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersPreferencesRepository extends BaseRepository
{
}
