<?php

namespace LoopAnime\UsersBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersRepository extends EntityRepository
{

    public function getUserPreferences() {
        return $this->createQueryBuilder("userPreferences")
            ->select("userPreferences")
            ->from("userPreferences", "userPreferences")
            ->where('userPreferences.user')
            ->getQuery()
            ->getResult();
    }

    public function getAllUsers($getQuery = true)
    {
        $query = $this->createQueryBuilder("users")
            ->select("users")
            ->getQuery();

        if($getQuery) {
            return $query;
        } else {
            return $query->getResult();
        }
    }

    public function getUser($idUser)
    {

        $query = $this->createQueryBuilder("users")
            ->select("users")
            ->from("users","users")
            ->where("users.id = :idUser")
            ->setParameter("idUser", $idUser)
            ->getQuery();

        return $query->getOneOrNullResult();

    }

}
