<?php

namespace LoopAnime\UsersBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersRepository extends EntityRepository
{

    public function getUserPreferences() {
        return $this->createQueryBuilder("userPreferences")
            ->select("userPreferences")
            ->from("userPreferences", "userPreferences")
            ->where('userPreferences.user')
            ->getQuery()
            ->getResult();
    }

}
