imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: "@LoopAnimeShowsAPIBundle/Resources/config/services.yml"}
    - { resource: liip/liip_imagine.yml }
framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        fos_csrf_provider: "@form.csrf_provider"
        transparent_1x1_gif: 'data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7'
        base_url: %base_url%

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        ["LoopAnimeWelcomeBundle"]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        cssmin:
          file: %kernel.root_dir%/../vendor/cssmin/cssmin-v3.0.1.php
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: LoopAnime\UsersBundle\Entity\Users
    registration:
            confirmation:
                enabled:    true
            form:
                handler: loopanime.registration.form.handler
                type: loopanime_user_registration

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: sliding.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

hwi_oauth:
    connect:
        account_connector: my_user_provider
    firewall_name: main
    fosub:
        username_iterations: 30
        properties:
            facebook: facebook_id
            google: google_id
    resource_owners:
        facebook:
            type:                facebook
            client_id:           "%facebook_appid%"
            client_secret:       "%facebook_secret%"
            scope:               "email user_location user_friends"
            infos_url:           "https://graph.facebook.com/me?fields=id,name,email,friends,picture,birthday,gender,locale"
            paths:
                email:            email
                profilepicture:  picture.data.url
        google:
            type:                google
            client_id:           "%google_appid%"
            client_secret:       "%google_secret%"
            scope:               "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/plus.login"

fos_oauth_server:
    db_driver: orm
    client_class:        LoopAnime\UsersBundle\Entity\Client
    access_token_class:  LoopAnime\UsersBundle\Entity\AccessToken
    refresh_token_class: LoopAnime\UsersBundle\Entity\RefreshToken
    auth_code_class:     LoopAnime\UsersBundle\Entity\AuthCode
    service:
        user_provider: my_user_provider
        options:
            supported_scopes: user
