<?php

namespace LoopAnime\CrawlersBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Animes_CrawlersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnimesCrawlersRepository extends EntityRepository
{
}
